FROM python:3.11-alpine

WORKDIR /app
# later
# RUN apk add --no-cache gcc musl-dev linux-headers

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN pip3 install --no-cache-dir --upgrade debugpy

EXPOSE 80
CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "--reload","app.main:app", "--host", "0.0.0.0", "--port", "80"]
